[package]
name = "mongo_schema_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
mongodb = "2.1"
once_cell = "1.10.0"
serde = "1"
