[package]
name = "mongo_schema_macro_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.13.1"
mongodb = "2.1"
proc-macro2 = "1.0.36"
quote = "1.0"
syn = { version = "1.0", features = ["derive"] }